using System;
using System.Globalization;
using EPiServer.Core;
using EPiServer.Web.Routing;
using PiNo.Labs.VariationsAuditor.Models;
using Microsoft.Extensions.Logging;

namespace PiNo.Labs.VariationsAuditor.Services
{
    // Builds a CMS 13 editor deep-link via the platform's EditUrlResolver so the full URL (host, shell module
    // base, content/language context) is generated by the CMS rather than hard-coded.
    public sealed class VariationEditUrlResolver : IVariationEditUrlResolver
    {
        private readonly EditUrlResolver _editUrlResolver;
        private readonly ILogger<VariationEditUrlResolver> _logger;

        public VariationEditUrlResolver(EditUrlResolver editUrlResolver, ILogger<VariationEditUrlResolver> logger)
        {
            _editUrlResolver = editUrlResolver;
            _logger = logger;
        }

        public string GetEditUrl(VariantIdentity identity)
        {
            if (identity == null)
            {
                return "/";
            }

            try
            {
                var contentLink = new ContentReference(identity.ContentId);
                var args = new EditUrlArguments();
                if (!string.IsNullOrEmpty(identity.LanguageBranch))
                {
                    args.Language = CultureInfo.GetCultureInfo(identity.LanguageBranch);
                }

                var url = _editUrlResolver.GetEditViewUrl(contentLink, args);
                return url?.ToString() is { Length: > 0 } s ? s : "/";
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Could not resolve the CMS edit URL for content {ContentId}.", identity.ContentId);
                return "/";
            }
        }
    }
}

